services:
  express:
    build: ./express-app
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=adminadmin
      - DB_NAME=realestate
    command: ["npm", "run", "dev"]
    networks:
      - app-network

  next-app:
    build: ./next-app
    ports:
      - "3001:3000"
    networks:
      - app-network

  # MySQL database
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: adminadmin
      MYSQL_DATABASE: realestate
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
